name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main
      - develop
      - feature/*

env:
  IMAGE_NAME: backend-api          # Replace with your desired image name
  REGISTRY: adarsh.azurecr.io    # Replace with your ACR registry URL

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
        TAG=$BRANCH_NAME-${{ github.run_id }}
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG .
        if [ "$BRANCH_NAME" = "main" ]; then
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        fi
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG
        if [ "$BRANCH_NAME" = "main" ]; then
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        fi
